### ISSUE TITLE
Command ds_create cannot find the directory `cfg/etc-bind`

### ISSUE THREAD

**Issue by RadZaeem** [docker-scripts/bind9#1]
`ds build` works OK.

However running `ds create`, I got this error. 
```
cp: cannot stat '/opt/docker-scripts/bind9/cfg/etc-bind': No such file or directory
Error response from daemon: invalid mount config for type "bind": bind source path does not exist
```

I am missing something? I cannot find that `cfg` folder

**Comment by dashohoxha** [comment]
@RadZaeem This is a bug. But it is easy to fix so I am assigning it to you.

When you create an issue, try to make the title more concise, since you can explain the details on the body.

**Comment by RadZaeem** [comment]
I have fixed the bug. Should I open a PR?

> When you create an issue, try to make the title more concise, since you can explain the details on the body.

OK, will do.

**Comment by dashohoxha** [comment]
> I have fixed the bug. Should I open a PR?

Yes, of course.

**Comment by dashohoxha** [comment]
Fixed by #2

**Comment by dashohoxha** [comment]
Actually, I think that moving directory `scripts/etc-bind` to `cfg/etc-bind` (and undoing the last change) would be better, because the directory `etc-bind` has no relation to `scripts`.

**Comment by RadZaeem** [comment]
made a PR here https://github.com/docker-scripts/bind9/pull/3
